---
title: "FGFR3 partner analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

# libraries
```{r}
library(dplyr)
library(ggplot2)
library(gridExtra)
library(patchwork)
```

# gene information from ensembl database
```{r}
ensembl = biomaRt::useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl", version = "100")
table_ensembl = biomaRt::getBM(attributes = c("ensembl_gene_id", "hgnc_symbol", "entrezgene_id", "uniprotswissprot", "ensembl_peptide_id"), mart = ensembl)
```


# loading data
```{r}
onco_data = R.utils::loadToEnv("~/Dropbox/Work_Netherlands/FGFR3/R/FM_FGFR3_RE_annotation.RData")[["onco_data"]]
onco_data_REs_trunc_with_partners = onco_data %>% 
    filter(FGFR3_RE_loc == "upstream", gene2_RE != "", !grepl(";", gene2_RE)) %>%
    mutate(Index = 1:nrow(.),
           gene2_EntrezID = table_ensembl$entrezgene_id[match(gene2_RE, table_ensembl$hgnc_symbol)],
           gene2_Ensembl = table_ensembl$ensembl_gene_id[match(gene2_RE, table_ensembl$hgnc_symbol)])

# genes unmatched symbol between bioMart and FM dataset
unmap_genes = c("AZI1" = "CEP131", "WHSC1" = "NSD2", "LARGE" = "LARGE1", "FAM129B" = "NIBAN2")

ind = match(onco_data_REs_trunc_with_partners$gene2_RE, names(unmap_genes))
ind_1 = ind[!is.na(ind)]
ind_2 = which(!is.na(ind))
onco_data_REs_trunc_with_partners$gene2_RE[ind_2] = unmap_genes[ind_1]
onco_data_REs_trunc_with_partners = onco_data_REs_trunc_with_partners %>% 
  mutate(gene2_EntrezID = table_ensembl$entrezgene_id[match(gene2_RE, table_ensembl$hgnc_symbol)],
         gene2_Ensembl = table_ensembl$ensembl_gene_id[match(gene2_RE, table_ensembl$hgnc_symbol)]) %>%
  mutate(gene2_EntrezID = ifelse(gene2_RE == "ZNF876P", 642280, gene2_EntrezID),
         gene2_Ensembl = ifelse(gene2_RE == "ZNF876P", "ENSG00000198155", gene2_Ensembl))

# FGFR3 partner genes
#write.table(onco_data_REs_trunc_with_partners, "~/FGFR3/nvim_R/data/FGFR3_trunc_REs_with_partners.txt", col.names = T, row.names = F, sep = "\t")

```
# SLIPPER scores for human proteome
```{r, fig.width=10, fig.height=4}
background = read.table("~/FGFR/Daniel/R/nvim_R/data/SLIPPER_background.txt", header = T, stringsAsFactors = F, sep = "\t", comment.char = "", quote = "")

partners = background %>% filter(Gene_symbol %in% unique(onco_data_REs_trunc_with_partners$gene2_RE))
t = table(onco_data_REs_trunc_with_partners$gene2_RE)
df = rbind(background %>% mutate(Frequency = 0, Type = "background", Group = "background"),
           partners %>% mutate(Frequency = t[match(partners$Gene_symbol, names(t))],
                               Type = rep(NA, nrow(partners)),
                                    Type = replace(Type, Frequency>=2, "Freq>=2"),
                                    Type = replace(Type, Frequency==1, "Freq=1"),
                                    Group = "partner"))
p_SLIPPER_1 = ggplot(df, aes(x = Score_rank, color = Type, fill = Type)) + geom_density(alpha = 0.1) + theme_classic()
p_SLIPPER_2 = ggplot(df, aes(x = Score_rank, color = Group, fill = Group)) + geom_density(alpha = 0.1) + theme_classic() +
  theme(axis.text.x = element_text(color = "black", size = 10),
        axis.text.y = element_text(color = "black", size = 10))
p_SLIPPER_1 + p_SLIPPER_2
```

# Self-interacting domains
```{r}
uniprot_prot = read.table("~/FGFR/Daniel/domain_interactions/uniprot-filtered-organism__Homo+sapiens+(Human)+[9606]_+AND+review--.tab", header = T, sep = "\t", stringsAsFactors = F,
                          fill = T, comment.char = "", quote = "") 

# SLIPPER SIP golden list
SLIPPER_SIP = xlsx::read.xlsx2("~/FGFR/Daniel/domain_interactions/Human SIP-direct_interaction-v20121201.xlsx", startRow = 2, sheetIndex = 1, header = T) %>%
  mutate(Interactor_A_entrez = table_ensembl$entrezgene_id[match(Interactor_A..SwissProt.AC., table_ensembl$uniprotswissprot)],
         Interactor_B_entrez = table_ensembl$entrezgene_id[match(Interactor_B..SwissProt.AC., table_ensembl$uniprotswissprot)])

# PPIDM database (domain-domain interactions)
PPIDM = read.csv2("~/FGFR/Daniel/domain_interactions/PPIDM_FullSortedDataset_84K_GSB.csv", sep = ",", stringsAsFactors = F, header = T)
PPIDM_self = PPIDM %>% filter(D1 == D2, CLASS == "Gold", IN_GOLDSTANDARD == "yes") %>% distinct()

# 3DID interacting domain
threedid = read.table("~/FGFR/Daniel/domain_interactions/3did_flat", header = F, sep = ",", stringsAsFactors = F, fill = T, comment.char = "", quote = "")
threedid = data.frame(stringr::str_split_fixed(threedid[grepl("#=ID", threedid[,1]),1], "\t", 5)[, 2:5]) %>%
  rename_all(~c("domain_1_name", "domain_2_name", "domain_1_pfam", "domain_2_pfam")) %>%
  mutate(domain_1_pfam = stringr::str_split_fixed(gsub("\\@Pfam| \\(", "", domain_1_pfam), "[.]", 2)[,1],
         domain_2_pfam = stringr::str_split_fixed(gsub("\\@Pfam|\\) ", "", domain_2_pfam), "[.]", 2)[,1])
threedid_self = unique(threedid %>% filter(domain_1_pfam == domain_2_pfam)) %>%
  distinct()

# Proteins with SID obtained from PPIDM and 3DID
SID = data.frame(t(matrix(unlist(
  lapply(uniprot_prot$Cross.reference..Pfam., function(X){
  t_ppidm = sum(unlist(strsplit(X, ";")) %in% PPIDM_self$D1)>0
  t_3did = sum(unlist(strsplit(X, ";")) %in% threedid_self$domain_1_pfam)>0
  c(t_ppidm, t_3did)})), 
  nrow = 2)))
colnames(SID) = c("SID_PPIDM", "SID_3did")

uniprot_prot = uniprot_prot %>% mutate(SID) %>% 
    mutate(SIP_SLIPPER = Entry %in% SLIPPER_SIP$Interactor_A..SwissProt.AC.,
         EntrezID = table_ensembl$entrezgene_id[match(Entry, table_ensembl$uniprotswissprot)],
         FGFR3_partner = EntrezID %in% unique(onco_data_REs_trunc_with_partners$gene2_EntrezID))

```

# Self-interacting protein percentage
```{r}
df = uniprot_prot %>%
  mutate(type = ifelse(EntrezID %in% unique(onco_data_REs_trunc_with_partners$gene2_EntrezID), "partner", "non-partner")) 

# Proportion of SI proteins among FGFR2 known partners and non-partners
df2 = df %>% group_by(type, SIP_SLIPPER) %>% summarise(n = n()) %>% 
  mutate(type = factor(type, levels = c("partner", "non-partner")))

df2 = rbind(data.frame(df2), 
            data.frame(type = "background", df2 %>% group_by(SIP_SLIPPER) %>% summarise(n = sum(n)))) %>%
  filter(type != "non-partner")

df2 = data.frame("type" = c("partner", "background"),
                 "n" = (df2 %>% group_by(type) %>% summarise(n = sum(n)) %>% pull(n)),
                 "x" = (df2 %>% filter(SIP_SLIPPER == TRUE) %>% pull(n)),
                 "SIP_perc" = (df2 %>% filter(SIP_SLIPPER == TRUE) %>% pull(n))*100 / (df2 %>% group_by(type) %>% summarise(n = sum(n)) %>% pull(n)))

p_bar = ggplot(df2, aes(x = type, y = SIP_perc)) + geom_bar(stat = "identity") + theme_classic() +
  theme(axis.text.x = element_text(color = "black", size = 12),
        axis.text.y = element_text(color = "black", size = 12))

p_bar

```

# Coiled-coil domains & SAM domain
```{r}
# Proportion of Coiled-coil proteins among FGFR3 partners and background
df_partner = uniprot_prot %>%
    filter(FGFR3_partner == T) %>% 
    mutate(CC_domain = ifelse(Coiled.coil != "", T, F)) %>%
    group_by(CC_domain) %>% summarise(n = n()) %>%
    mutate(freq = n / sum(n)) %>% filter(CC_domain == T)
df_background = uniprot_prot %>%
    mutate(CC_domain = ifelse(Coiled.coil != "", T, F)) %>%
    group_by(CC_domain) %>% summarise(n = n()) %>%
    mutate(freq = n / sum(n)) %>% filter(CC_domain == T)

df = rbind(data.frame(type = "background", df_background),
           data.frame(type = "FGFR3 partners", df_partner))

p_bar_CC = ggplot(df, aes(x = type, y = freq)) + geom_bar(stat = "identity") + theme_classic() +
  theme(axis.text.x = element_text(color = "black", size = 12),
        axis.text.y = element_text(color = "black", size = 12)) +
  ggtitle("% of Coiled-coil")


# Proportion of Coiled-coil proteins among FGFR3 partners and background
df_partner = uniprot_prot %>%
    filter(FGFR3_partner == T) %>% 
    mutate(CC_SAM_domain = ifelse(Coiled.coil != "" | grepl("PF00536", Cross.reference..Pfam.), T, F)) %>%
    group_by(CC_SAM_domain) %>% summarise(n = n()) %>%
    mutate(freq = n / sum(n)) %>% filter(CC_SAM_domain == T)
df_background = uniprot_prot %>%
    mutate(CC_SAM_domain = ifelse(Coiled.coil != "" | grepl("PF00536", Cross.reference..Pfam.), T, F)) %>%
    group_by(CC_SAM_domain) %>% summarise(n = n()) %>%
    mutate(freq = n / sum(n)) %>% filter(CC_SAM_domain == T)

df = rbind(data.frame(type = "background", df_background),
           data.frame(type = "FGFR3 partners", df_partner))

p_bar_CC_SAM = ggplot(df, aes(x = type, y = freq)) + geom_bar(stat = "identity") + theme_classic() +
  theme(axis.text.x = element_text(color = "black", size = 12),
        axis.text.y = element_text(color = "black", size = 12)) +
  ggtitle("% of Coiled-coil & SAM")


p_bar_CC + p_bar_CC_SAM

pdf("~/FGFR3/nvim_R/figures/CC_domain_barplot.pdf", width = 5, height = 4)
p_bar_CC
dev.off()

```



# DAVID domain-enrichment analysis
```{r}
library(RDAVIDWebService)
partner_genes = unique(onco_data_REs_trunc_with_partners$gene2_EntrezID)

david <- DAVIDWebService$new(email='j.bhin@nki.nl', url="https://david.ncifcrf.gov/webservice/services/DAVIDWebService")
FG_partner <- addList(david, partner_genes, idType="ENTREZ_GENE_ID", listName ="isClass", listType="Gene")

setAnnotationCategories(david, c("PFAM"))
FuncAnnotChart <- getFunctionalAnnotationChart(david, threshold=1, count=1L)
FuncAnnotChart = data.frame(FuncAnnotChart) %>% 
  mutate(Pfam_ID = stringr::str_split_fixed(Term, ":", 2)[,1],
         SI_domain = ifelse(Pfam_ID %in% intersect(PPIDM_self$D1, threedid_self$domain_1_pfam), T, F),
         #SI_domain = ifelse(Pfam_ID %in% unique(c(PPIDM_self$D1)), T, F),
         Term = stringr::str_split_fixed(Term, ":", 2)[,2])

# presenting significant & SI domains
FuncAnnotChart_sig = FuncAnnotChart %>% arrange(PValue) %>% filter(PValue<0.05) %>%
  mutate(Term = factor(Term, levels = rev(Term))) %>% filter(SI_domain == T)
  

# loading DAVID Pfam results for FGFR2 non-partners
FuncAnnotChart_background = read.table("~/FGFR/Daniel/domain_interactions/DAVID_background.txt", header = T, sep = "\t", stringsAsFactors = F, quote = "", fill = T)
FuncAnnotChart_background = FuncAnnotChart_background %>% 
  mutate(Pfam_ID = stringr::str_split_fixed(Term, ":", 2)[,1],
         Term = stringr::str_split_fixed(Term, ":", 2)[,2],
         SI_domain = ifelse(Pfam_ID %in% intersect(PPIDM_self$D1, threedid_self$domain_1_pfam), T, F))

df = rbind(data.frame(FuncAnnotChart_sig[, c("Term", "Pfam_ID", "Count", "PValue", "X.")], 
                      Group = "Partner"),
           data.frame(FuncAnnotChart_sig[, c("Term", "Pfam_ID")],
                      FuncAnnotChart_background[match(FuncAnnotChart_sig$Pfam_ID, FuncAnnotChart_background$Pfam_ID), c("Count", "PValue", "X.")], 
                      Group = "Background")) %>%
  rename_all(~c("Term", "Pfam_ID", "Count", "PValue", "Perc", "Group")) %>%
  mutate(Count = replace(Count, is.na(Count), 0), PValue = replace(PValue, is.na(PValue), 1), Perc = replace(Perc, is.na(Perc), 0))


p1 = df %>% 
  ggplot(aes(x = Term, y = -log10(PValue), fill = Group)) + geom_bar(stat = "identity", position=position_dodge()) + 
  ggtitle("-log10(P-value)") + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(), 
        plot.margin = unit(c(1,1,1,1), "mm"),
        legend.position="bottom") +
  coord_flip() + scale_y_reverse(breaks = seq.int(10,0,by = -2)) + geom_hline(yintercept = -log10(0.05), linetype = "dotted", col = "red")

p2 = df %>% 
  ggplot(aes(x = Term, y = Perc, fill = Group)) + geom_bar(stat = "identity", position=position_dodge()) + 
  ggtitle("Percentage") + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(), 
        axis.text.y = element_blank(), axis.ticks.y = element_blank(), 
        plot.margin = unit(c(1,1,1,1), "mm"),
        legend.position = "bottom") + 
  coord_flip() 


p_mid = ggplot(FuncAnnotChart_sig, aes(x = 1, y = Term)) + geom_text(aes(label = Term)) +
  #geom_segment(aes(x=0.94,xend=0.96,yend=Term))+
  #geom_segment(aes(x=1.04,xend=1.065,yend=Term))+
  ggtitle("")+
  ylab(NULL)+
  scale_x_continuous(expand=c(0,0),limits=c(0.8,1.2))+
  theme(axis.title=element_blank(),
        panel.grid=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        axis.text.x=element_text(color=NA),
        axis.ticks.x=element_line(color=NA),
        plot.margin = unit(c(2,-1,15,-1), "mm")) +
  theme(legend.position = "bottom")

gg1 = ggplot_gtable(ggplot_build(p1))
gg2 = ggplot_gtable(ggplot_build(p2))
gg.mid = ggplot_gtable(ggplot_build(p_mid))
grid.arrange(gg1, gg.mid, gg2, ncol=3, widths=c(1/3, 1.5/3, 1/3))
```

# Distribution of FGFR3 partners
```{r}
donuts <- function(x, group = 1, labels = NA, col = NULL, radius = c(.7, 1)) {
  group <- rep_len(group, length(x))
  ug  <- unique(group)
  tbl <- table(group)[order(ug)]

  col <- if (is.null(col))
    seq_along(ug) else rep_len(col, length(ug))
  col.main <- Map(rep, col[seq_along(tbl)], tbl)
  col.sub  <- lapply(col.main, function(x) {
    al <- head(seq(0, 1, length.out = length(x) + 2L)[-1L], -1L)
    Vectorize(adjustcolor)(x, alpha.f = al)
  })

  plot.new()

  par(new = TRUE)
  pie(x, border = NA, radius = radius[2L],
      col = unlist(col.sub), labels = labels, cex = 0.7)

  par(new = TRUE)
  pie(x, border = NA, radius = radius[1L],
      col = unlist(col.main), labels = NA)
}
```

# Self-interacting domain + uniprot coild-coil domain
```{r, fig.width=10, fig.height=10}
###############################################
# SID domain
###############################################
df = onco_data_REs_trunc_with_partners %>%
    mutate(SID = gene2_EntrezID %in% (uniprot_prot %>% filter((SID_PPIDM == T & SID_3did == T) | Coiled.coil !="") %>% pull(EntrezID))) %>%
    mutate(group = ifelse(gene2_EntrezID %in% (uniprot_prot %>% filter(Coiled.coil !="") %>% pull(EntrezID)), "Coiled-coil", NA),
           group = replace(group, is.na(group) & SID== T, "SID"),
           group = replace(group, is.na(group), "Non-SID"),
           group = factor(group, levels = c("Coiled-coil", "SID", "Non-SID")))

df_1 = df %>%
    mutate(PARTNER_label = ifelse(gene2_RE %in% (names(which(table(df$gene2_RE)>=2))), gene2_RE, "others"),
           PARTNER_label = factor(PARTNER_label, levels = c(names(which(sort(table(df$gene2_RE), decreasing=T)>=2)), "others"))) %>%
    group_by(group, PARTNER_label) %>% summarise(n = n())

df_intergenic = onco_data %>% filter(FGFR3_RE_loc == "upstream", gene2_RE == "") %>%
    mutate(PARTNER_label = "intergenic", group = "intergenic") %>%
    group_by(group, PARTNER_label) %>% summarise(n = n())

df_comb = rbind(data.frame(df_1),
                data.frame(df_intergenic)) %>%
    mutate(group = factor(group, levels = c("Coiled-coil", "SID", "Non-SID", "intergenic")))

#pdf("~/FGFR3/nvim_R/figures/donuts_partners.pdf", width = 10, height = 10)
with(rev(df_comb), donuts(n, group, paste(PARTNER_label, " (", n, ")"), col = c("#F8766D", "#FFB266", "#C49A00", "#FF66FF", radius = c(0.3, 2))))
#dev.off()


```

# Coild-coil domain
```{r, fig.width=10, fig.height=10}
df = onco_data_REs_trunc_with_partners %>%
    mutate(CC_domain = gene2_EntrezID %in% (uniprot_prot %>% filter(Coiled.coil != "") %>% pull(EntrezID)))
df_CC = df %>% filter(CC_domain == T)
df_CC = df_CC %>% 
    mutate(PARTNER_label = ifelse(gene2_RE %in% (names(which(table(df_CC$gene2_RE)>=2))), gene2_RE, "others"),
           PARTNER_label = factor(PARTNER_label, levels = c(names(which(sort(table(df_CC$gene2_RE), decreasing=T)>=2)), "others"))) %>%
    group_by(PARTNER_label) %>% summarise(n = n())

df_NCC = df %>% filter(CC_domain == F)
df_NCC = df_NCC %>% 
    mutate(PARTNER_label = ifelse(gene2_RE %in% (names(which(table(df_NCC$gene2_RE)>=2))), gene2_RE, "others"),
           PARTNER_label = factor(PARTNER_label, levels = c(names(which(sort(table(df_NCC$gene2_RE), decreasing=T)>=2)), "others"))) %>%
    group_by(PARTNER_label) %>% summarise(n = n())

df_intergenic = onco_data %>% filter(FGFR3_RE_loc == "upstream", gene2_RE == "") %>%
    mutate(PARTNER_label = "intergenic") %>%
    group_by(PARTNER_label) %>% summarise(n = n())

df_comb = rbind(data.frame(df_CC, group = "Coild-coil"),
                data.frame(df_NCC, group = "No coiled-coil"), 
                data.frame(df_intergenic, group = "intergenic"))
#pdf("~/FGFR3/nvim_R/figures/donuts_partners.pdf")
with(rev(df_comb), donuts(n, group, paste(PARTNER_label, " (", n, ")", sep=""), col = c("#F8766D", "#C49A00", "#FF66FF", radius = c(0.3, 2))))
#dev.off()


```

# Coiled-coil & SAM domains
```{r, fig.width=10, fig.height=10}
df = onco_data_REs_trunc_with_partners %>%
    mutate(CC_SAM_domain = gene2_EntrezID %in% (uniprot_prot %>% filter(Coiled.coil != "" | grepl("PF00536", Cross.reference..Pfam.)) %>% pull(EntrezID)))
df_CC_SAM = df %>% filter(CC_SAM_domain == T)
df_CC_SAM = df_CC_SAM %>% 
    mutate(PARTNER_label = ifelse(gene2_RE %in% (names(which(table(df_CC_SAM$gene2_RE)>=2))), gene2_RE, "others"),
           PARTNER_label = factor(PARTNER_label, levels = c(names(which(sort(table(df_CC_SAM$gene2_RE), decreasing=T)>=2)), "others"))) %>%
    group_by(PARTNER_label) %>% summarise(n = n())

df_CC_SAM_N = df %>% filter(CC_SAM_domain == F)
df_CC_SAM_N = df_CC_SAM_N %>% 
    mutate(PARTNER_label = ifelse(gene2_RE %in% (names(which(table(df_CC_SAM_N$gene2_RE)>=2))), gene2_RE, "others"),
           PARTNER_label = factor(PARTNER_label, levels = c(names(which(sort(table(df_CC_SAM_N$gene2_RE), decreasing=T)>=2)), "others"))) %>%
    group_by(PARTNER_label) %>% summarise(n = n())

df_intergenic = onco_data %>% filter(FGFR3_RE_loc == "upstream", gene2_RE == "") %>%
    mutate(PARTNER_label = "intergenic") %>%
    group_by(PARTNER_label) %>% summarise(n = n())

df_comb = rbind(data.frame(df_CC_SAM, group = "Coild-coil & SAM"),
                data.frame(df_CC_SAM_N, group = "No coiled-coil & SAM"), 
                data.frame(df_intergenic, group = "intergenic"))
#pdf("~/FGFR3/nvim_R/figures/donuts_partners.pdf")
with(rev(df_comb), donuts(n, group, paste(PARTNER_label, n), col = c("#F8766D", "#C49A00", "#FF66FF", radius = c(0.3, 2))))


```

