---
title: "Untitled"
output: html_document
date: "2024-01-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libraries
```{r}
library(dplyr)
library(GenomicRanges)
library(ggplot2)
```

```{r}
hg19_info = R.utils::loadToEnv("~/Dropbox/Work_Netherlands/FGFR3/R/HMF_data_purple_FGFR3.RData")[["hg19_info"]]
txid = hg19_info$trx_gene_AA_major %>% filter(SYMBOL == "FGFR3") %>% pull(TXID)


FGFR3_CDS = hg19_info$G_cds[['17460']]
FGFR3_CDS$id = paste0("E", 2:18)

```


```{r}
Mut = read.table("~/Dropbox/Work_Netherlands/FGFR3/FGFR3_Trunc_Mut_total.txt", header = T, sep = "\t", stringsAsFactors = F, quote = "")
Mut = Mut %>% filter(!grepl("None", Genomic_coordinate))
Mut = GRanges(data.frame(chr = stringr::str_split_fixed(Mut$Genomic_coordinate, ":", 2)[,1],
                         start = stringr::str_split_fixed(Mut$Genomic_coordinate, ":", 2)[,2],
                         end = stringr::str_split_fixed(Mut$Genomic_coordinate, ":", 2)[,2],
                         Mut))

# data.frame for mutation count
t = table(FGFR3_CDS$id[subjectHits(findOverlaps(Mut, FGFR3_CDS))])
df_trunc = data.frame(Exon = paste0("E", 2:18),
                      Length = width(FGFR3_CDS)) %>%
  mutate(Counts = t[match(Exon, names(t))])
df_trunc$Counts[is.na(df_trunc$Counts)] = 0
df_trunc$n_kb = (1000*df_trunc$Counts)/(df_trunc$Length * length(Mut))


# binomial test
prob_bino = df_trunc$Length/sum(df_trunc$Length)
pval_bino = numeric(nrow(df_trunc))
for(i in 1:length(prob_bino)){
  t = binom.test(x = df_trunc$Counts[i], n = sum(df_trunc$Counts), p = prob_bino[i], alternative = "greater")
  pval_bino[i] = t$p.value
}

df_trunc$pval = -log10(pval_bino)
df_trunc_along = tidyr::gather(df_trunc, key="measure", value="value", c("n_kb", "pval"))
df_trunc_along$Exon = factor(df_trunc_along$Exon, levels = paste0("E", 2:18))

ggplot(df_trunc_along, aes(x=Exon, y=value)) + geom_bar(stat='identity')+
  facet_wrap(~measure,  ncol=1, scales = "free") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme_classic()


```


